-- ==========================================
-- SUPABASE SQL SCHEMA FOR REFF INK
-- ==========================================

-- 1. Table: website_settings
CREATE TABLE IF NOT EXISTS public.website_settings (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama_toko text,
    tentang_kami text,
    alamat text,
    nomor_wa text,
    logo_url text,
    banner_title text,
    banner_subtitle text,
    banner_image_url text,
    keunggulan_teks text,
    cta_teks text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initialize default website settings
INSERT INTO public.website_settings (id, nama_toko, tentang_kami, alamat, nomor_wa, banner_title, banner_subtitle, keunggulan_teks, cta_teks)
VALUES (
    1, 
    'REFF INK', 
    'REFF INK adalah pusat layanan printer dan isi ulang tinta profesional. Kami melayani perbaikan printer berbagai merk dengan teknisi handal dan garansi service.', 
    'Jl. Contoh Alamat No. 123, Kota', 
    '6281234567890', 
    'Solusi Terbaik untuk<br>Printer Anda', 
    'Layanan isi ulang tinta, service printer, dan perawatan printer terbaik. Kami mengatasi masalah printer Anda dengan cepat dan bergaransi.', 
    'Kami menggunakan tinta berkualitas tinggi dan sparepart original. Proses pengerjaan cepat dan bergaransi.', 
    'Hubungi kami sekarang untuk mendapatkan estimasi perbaikan secara gratis.'
) ON CONFLICT (id) DO NOTHING;

-- 2. Table: services
CREATE TABLE IF NOT EXISTS public.services (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nama text NOT NULL,
    deskripsi text,
    icon text,
    image_url text,
    is_unggulan boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Table: pricing
CREATE TABLE IF NOT EXISTS public.pricing (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kategori text NOT NULL, -- 'tinta', 'jasa', 'sparepart'
    nama text NOT NULL,
    keterangan text,
    harga text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Table: promos
CREATE TABLE IF NOT EXISTS public.promos (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    judul text NOT NULL,
    deskripsi text,
    harga_awal text,
    harga_promo text NOT NULL,
    badge text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Table: gallery
CREATE TABLE IF NOT EXISTS public.gallery (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    image_url text NOT NULL,
    category text,
    caption text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Table: faqs
CREATE TABLE IF NOT EXISTS public.faqs (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question text NOT NULL,
    answer text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Table: testimonials
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rating smallint NOT NULL DEFAULT 5,
    review text NOT NULL,
    customer_name text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enable read access for public users
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.promos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- Create Select Policies (Everyone can read)
DROP POLICY IF EXISTS "Public read website_settings" ON public.website_settings;
CREATE POLICY "Public read website_settings" ON public.website_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read services" ON public.services;
CREATE POLICY "Public read services" ON public.services FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read pricing" ON public.pricing;
CREATE POLICY "Public read pricing" ON public.pricing FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read promos" ON public.promos;
CREATE POLICY "Public read promos" ON public.promos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read gallery" ON public.gallery;
CREATE POLICY "Public read gallery" ON public.gallery FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read faqs" ON public.faqs;
CREATE POLICY "Public read faqs" ON public.faqs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read testimonials" ON public.testimonials;
CREATE POLICY "Public read testimonials" ON public.testimonials FOR SELECT USING (true);

-- Create Authentication Policies for Admins to INSERT/UPDATE/DELETE
-- For promos
DROP POLICY IF EXISTS "Admin can insert promos" ON public.promos;
CREATE POLICY "Admin can insert promos" ON public.promos FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can update promos" ON public.promos;
CREATE POLICY "Admin can update promos" ON public.promos FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete promos" ON public.promos;
CREATE POLICY "Admin can delete promos" ON public.promos FOR DELETE USING (auth.role() = 'authenticated');

-- For website_settings
DROP POLICY IF EXISTS "Admin can insert website_settings" ON public.website_settings;
CREATE POLICY "Admin can insert website_settings" ON public.website_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can update website_settings" ON public.website_settings;
CREATE POLICY "Admin can update website_settings" ON public.website_settings FOR UPDATE USING (auth.role() = 'authenticated');

-- For services
DROP POLICY IF EXISTS "Admin can insert services" ON public.services;
CREATE POLICY "Admin can insert services" ON public.services FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can update services" ON public.services;
CREATE POLICY "Admin can update services" ON public.services FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete services" ON public.services;
CREATE POLICY "Admin can delete services" ON public.services FOR DELETE USING (auth.role() = 'authenticated');

-- For pricing
DROP POLICY IF EXISTS "Admin can insert pricing" ON public.pricing;
CREATE POLICY "Admin can insert pricing" ON public.pricing FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can update pricing" ON public.pricing;
CREATE POLICY "Admin can update pricing" ON public.pricing FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete pricing" ON public.pricing;
CREATE POLICY "Admin can delete pricing" ON public.pricing FOR DELETE USING (auth.role() = 'authenticated');

-- For gallery
DROP POLICY IF EXISTS "Admin can insert gallery" ON public.gallery;
CREATE POLICY "Admin can insert gallery" ON public.gallery FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete gallery" ON public.gallery;
CREATE POLICY "Admin can delete gallery" ON public.gallery FOR DELETE USING (auth.role() = 'authenticated');

-- For faqs
DROP POLICY IF EXISTS "Admin can insert faqs" ON public.faqs;
CREATE POLICY "Admin can insert faqs" ON public.faqs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can update faqs" ON public.faqs;
CREATE POLICY "Admin can update faqs" ON public.faqs FOR UPDATE USING (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete faqs" ON public.faqs;
CREATE POLICY "Admin can delete faqs" ON public.faqs FOR DELETE USING (auth.role() = 'authenticated');

-- For testimonials
DROP POLICY IF EXISTS "Admin can insert testimonials" ON public.testimonials;
CREATE POLICY "Admin can insert testimonials" ON public.testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');
DROP POLICY IF EXISTS "Admin can delete testimonials" ON public.testimonials;
CREATE POLICY "Admin can delete testimonials" ON public.testimonials FOR DELETE USING (auth.role() = 'authenticated');

-- ==========================================
-- SUPABASE STORAGE FOR IMAGES
-- ==========================================

-- Create bucket "public_images"
insert into storage.buckets (id, name, public)
values ('public_images', 'public_images', true)
on conflict (id) do nothing;

-- Create policy to allow public read access
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'public_images' );

-- Create policy to allow authenticated users to upload
DROP POLICY IF EXISTS "Authenticated users can upload" ON storage.objects;
create policy "Authenticated users can upload"
on storage.objects for insert
with check ( bucket_id = 'public_images' and auth.role() = 'authenticated' );

-- Create policy to allow authenticated users to update
DROP POLICY IF EXISTS "Authenticated users can update" ON storage.objects;
create policy "Authenticated users can update"
on storage.objects for update
using ( bucket_id = 'public_images' and auth.role() = 'authenticated' );

-- Create policy to allow authenticated users to delete
DROP POLICY IF EXISTS "Authenticated users can delete" ON storage.objects;
create policy "Authenticated users can delete"
on storage.objects for delete
using ( bucket_id = 'public_images' and auth.role() = 'authenticated' );

-- ==========================================
-- SUPABASE SQL SCHEMA FOR SERVICE TRACKING
-- ==========================================

-- 8. Table: service_tracking
CREATE TABLE IF NOT EXISTS public.service_tracking (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    no_nota text UNIQUE NOT NULL,
    nama_pelanggan text NOT NULL,
    nomor_wa text,
    tipe_printer text NOT NULL,
    keluhan text,
    status text NOT NULL DEFAULT 'menunggu', -- 'menunggu', 'dicek', 'diperbaiki', 'selesai', 'diambil'
    biaya text DEFAULT '0',
    teknisi text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.service_tracking ENABLE ROW LEVEL SECURITY;

-- Create Select Policy (Everyone can read for tracking page)
DROP POLICY IF EXISTS "Public read service_tracking" ON public.service_tracking;
CREATE POLICY "Public read service_tracking" ON public.service_tracking FOR SELECT USING (true);

-- Create policies for authenticated users to insert, update, and delete
DROP POLICY IF EXISTS "Admin can insert service_tracking" ON public.service_tracking;
CREATE POLICY "Admin can insert service_tracking" ON public.service_tracking FOR INSERT WITH CHECK (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin can update service_tracking" ON public.service_tracking;
CREATE POLICY "Admin can update service_tracking" ON public.service_tracking FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Admin can delete service_tracking" ON public.service_tracking;
CREATE POLICY "Admin can delete service_tracking" ON public.service_tracking FOR DELETE USING (auth.role() = 'authenticated');

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_service_tracking_updated_at ON public.service_tracking;
CREATE TRIGGER update_service_tracking_updated_at
BEFORE UPDATE ON public.service_tracking
FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
